apiVersion: circlerr.io/v1alpha1
kind: Circle
metadata:
  name: circle-2
spec:
  author: Maycon Pacheco
  description: Lorem ipsum
  namespace: default
  modules:
    - name: module-1
      revision: revision-2
      namespace: default
  environments:
    - key: API_URL
      value: http://localhost:8000/api