name: CI
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Build
        run: go build -v ./...

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        
